apiVersion: v1
kind: Service
metadata:
  name: status-service
  labels:
    app: status-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: status-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
