apiVersion: v1
kind: Service
metadata:
  name: status-service
  labels:
    app: status-service
spec:
  type: ClusterIP
  selector:
    app: status-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
